<?php

namespace App\Tenants\Modules\HRM\Controllers;

use App\Http\Controllers\Controller;
use App\Tenants\Modules\HRM\Models\Employee;
use App\Tenants\Modules\HRM\Services\EmployeeService;
use DomainException;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    public function __construct(protected EmployeeService $service) {}

    public function index(Request $request)
    {
        $query = Employee::query()
            ->with(['department:id,name', 'position:id,title', 'manager:id,first_name,last_name']);

        if ($request->filled('q')) {
            $term = '%' . $request->string('q') . '%';
            $query->where(function ($q) use ($term) {
                $q->where('first_name', 'ilike', $term)
                  ->orWhere('last_name', 'ilike', $term)
                  ->orWhere('email', 'ilike', $term)
                  ->orWhere('employee_id', 'ilike', $term);
            });
        }
        if ($request->filled('department_id')) {
            $query->where('department_id', $request->string('department_id'));
        }
        if ($request->filled('status')) {
            $query->where('status', $request->string('status'));
        }

        return response()->json([
            'data' => $query->orderBy('first_name')->paginate($request->integer('per_page', 25)),
        ]);
    }

    public function show(Employee $employee)
    {
        return response()->json([
            'data' => $employee->load(['department', 'position', 'manager:id,first_name,last_name', 'user:id,email,handle']),
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->validate($this->rules());
        $employee = $this->service->create($data);
        return response()->json(['success' => true, 'data' => $employee], 201);
    }

    public function update(Request $request, Employee $employee)
    {
        $data = $request->validate($this->rules($employee));
        try {
            $employee = $this->service->update($employee, $data);
        } catch (DomainException $e) {
            return response()->json(['success' => false, 'message' => $e->getMessage()], 422);
        }
        return response()->json(['success' => true, 'data' => $employee]);
    }

    public function destroy(Request $request, Employee $employee)
    {
        try {
            $this->service->terminateEmployee($employee, $request->input('reason'), $request->input('effective_at'));
        } catch (DomainException $e) {
            return response()->json(['success' => false, 'message' => $e->getMessage()], 422);
        }
        return response()->json(['success' => true]);
    }

    public function restore(string $id)
    {
        $employee = Employee::withTrashed()->findOrFail($id);
        try {
            $restored = $this->service->restoreEmployee($employee);
        } catch (DomainException $e) {
            return response()->json(['success' => false, 'message' => $e->getMessage()], 422);
        }
        return response()->json(['success' => true, 'data' => $restored]);
    }

    private function rules(?Employee $employee = null): array
    {
        $emailRule = 'required|email|max:160';
        if ($employee) {
            $emailRule .= '|unique:employees,email,' . $employee->id . ',id,deleted_at,NULL';
        } else {
            $emailRule .= '|unique:employees,email,NULL,id,deleted_at,NULL';
        }

        return [
            // Optional on both create and update — auto-generated by EmployeeService
            // when omitted on create (recruitment-style `TT-NNNN` sequence).
            'employee_id'      => 'sometimes|nullable|string|max:32|unique:employees,employee_id' . ($employee ? ',' . $employee->id : ''),
            'first_name'       => ($employee ? 'sometimes' : 'required') . '|string|max:80',
            'last_name'        => ($employee ? 'sometimes' : 'required') . '|string|max:80',
            'email'            => $employee ? str_replace('required', 'sometimes', $emailRule) : $emailRule,
            'phone'            => 'nullable|string|max:32',
            'date_of_birth'    => 'nullable|date|before:today',
            'gender'           => 'nullable|in:male,female,other,prefer_not_to_say',
            'national_id'      => 'nullable|string|max:64',
            'bank_account'     => 'nullable|string|max:64',
            'tax_id'           => 'nullable|string|max:64',
            'address'          => 'nullable|string|max:255',
            'city'             => 'nullable|string|max:120',
            'country'          => 'nullable|string|max:64',
            'department_id'    => 'nullable|uuid|exists:departments,id',
            'position_id'      => 'nullable|uuid|exists:positions,id',
            'manager_id'       => 'nullable|uuid|exists:employees,id',
            'user_id'          => 'nullable|uuid|exists:users,id',
            'hire_date'        => 'nullable|date',
            'employment_type'  => 'nullable|in:full_time,part_time,contract,intern',
            'status'           => 'nullable|string|max:32',
            'base_salary'      => 'nullable|numeric|min:0',
            'currency'         => 'nullable|string|size:3',
            'pay_frequency'    => 'nullable|in:weekly,biweekly,monthly',
        ];
    }
}
